config/routes.rb
Rails.application.routes.draw do
  resources :bricks
end

app/models/brick.rb
class Brick < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bricks_controller.rb
class BricksController < ApplicationController
  before_action :set_brick, only: [:show, :edit, :update, :destroy]

  # GET /bricks
  # GET /bricks.json
  def index
    @bricks = Brick.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /bricks/1
  # GET /bricks/1.json
  def show
  end

  # GET /bricks/new
  def new
    @brick = Brick.new
  end

  # GET /bricks/1/edit
  def edit
  end

  # POST /bricks
  # POST /bricks.json
  def create
    @brick = Brick.new(brick_params)

    respond_to do |format|
      if @brick.save
        format.html { redirect_to @brick, notice: 'Brick was successfully created.' }
        format.json { render :show, status: :created, location: @brick }
      else
        format.html { render :new }
        format.json { render json: @brick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bricks/1
  # PATCH/PUT /bricks/1.json
  def update
    respond_to do |format|
      if @brick.update(brick_params)
        format.html { redirect_to @brick, notice: 'Brick was successfully updated.' }
        format.json { render :show, status: :ok, location: @brick }
      else
        format.html { render :edit }
        format.json { render json: @brick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bricks/1
  # DELETE /bricks/1.json
  def destroy
    @brick.destroy
    respond_to do |format|
      format.html { redirect_to bricks_url, notice: 'Brick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brick
      @brick = Brick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brick_params
      params.require(:brick).permit(:set_number, :name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bricks_helper.rb
module BricksHelper
end

app/views/bricks/_form.html.erb
<%= form_for(@brick) do |f| %>
  <% if @brick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brick.errors.count, "error") %> prohibited this brick from being saved:</h2>

      <ul>
      <% @brick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :set_number %><br>
    <%= f.number_field :set_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bricks/edit.html.erb
<h1>Editing Brick</h1>

<%= render 'form' %>

<%= link_to 'Show', @brick %> |
<%= link_to 'Back', bricks_path %>

app/views/bricks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h4>Listing bricks</h4>
      </div>
      <div class="col-xs-6">
        <h4><%= link_to 'New Brick', new_brick_path %></h4>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Set number</th>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th class="td-actions text-right">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @bricks.each do |brick| %>
          <tr>
            <td><%= brick.set_number %></td>
            <td><%= brick.name %></td>
            <td><%= brick.description %></td>
            <td><%= brick.price %></td>
            <td><%= link_to 'Show', brick %></td>
            <td><%= link_to 'Edit', edit_brick_path(brick) %></td>
            <td><%= link_to 'Destroy', brick, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>

        <% if @bricks.length == 0 %>
          <tr><td colspan=42 class='text-center'>No bricks.</td></tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= will_paginate @bricks, class: "pagination pagination-no-border" if @bricks.respond_to?(:total_pages) %>

app/views/bricks/new.html.erb
<h1>New Brick</h1>

<%= render 'form' %>

<%= link_to 'Back', bricks_path %>

app/views/bricks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <div class="container">
    <h2>Showing brick</h2>
  </div>
</div>

<div class="container">
  <div class="form-horizontal">
    <div class="form-group">
      <label class="col-md-2 control-label">Set number</label>
      <div class="col-md-10">
        <div class="form-control">
          <span>
            <%= @brick.set_number %>
          </span>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-2 control-label">Name</label>
      <div class="col-md-10">
        <div class="form-control">
          <span>
            <%= @brick.name %>
          </span>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-2 control-label">Description</label>
      <div class="col-md-10">
        <div class="form-control">
          <span>
            <%= @brick.description %>
          </span>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-2 control-label">Price</label>
      <div class="col-md-10">
        <div class="form-control">
          <span>
            <%= @brick.price %>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="form-actions col-md-offset-2 col-md-10">
    <%= link_to 'Edit', edit_brick_path(@brick) %> |
<%= link_to 'Back', bricks_path %>
  </div>
</div>

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Get Shit Done Kit by Creative Tim</title>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//google-code-prettify.googlecode.com/svn/loader/run_prettify.js" %>

    <%= yield :style %>
  </head>
  <body data-features="<%= yield :features %>" class="<%= yield :class %>">

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brickstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>